#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99
END=99

start() {
	echo "${initscript}: Starting adblock..."
	timeout=60
	for i in $(seq $timeout); do
		sleep 1
		[ $i == $timeout ] && exit 1
		if [ $( cat /sys/class/net/eth0/operstate ) == "up" ] ; then
			if ! grep -q "adblock" /etc/crontabs/root
			then
        		# Turn on
        		sh /etc/adblock.sh -t > /dev/null 2>&1
   			fi
			sh /etc/adblock.sh > /dev/null 2>&1
			exit 1
		fi
	done
}

stop() {
	echo "${initscript}: stopping adblock..."
	if grep -q "adblock" /etc/crontabs/root
	then
        # Turn off
        sh /etc/adblock.sh -t > /dev/null 2>&1
    fi
}